# Generated by Django 3.2.9 on 2022-02-14 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizModel',
            fields=[
                ('Quiz_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Course_ID', models.CharField(max_length=200, null=True)),
                ('Quiz_name', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResultModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marks', models.IntegerField()),
                ('Quiz_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmodel')),
            ],
        ),
        migrations.CreateModel(
            name='QuesModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('option1', models.CharField(max_length=20)),
                ('option2', models.CharField(max_length=20)),
                ('option3', models.CharField(max_length=20)),
                ('option4', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('Quiz_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quizmodel')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerModel',
            fields=[
                ('Answer_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Answer', models.CharField(max_length=200, null=True)),
                ('isCorrect', models.BooleanField(default=True)),
                ('Question_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.quesmodel')),
            ],
        ),
    ]
