# Generated by Django 3.2.9 on 2022-05-25 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='Course_ID',
        ),
        migrations.AddField(
            model_name='quizmodel',
            name='course',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.course'),
            preserve_default=False,
        ),
    ]
