# Generated by Django 3.2.9 on 2022-04-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0003_submitassignment_assignment_ques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submitassignment',
            name='assignment_name',
        ),
    ]
