# Generated by Django 3.2.9 on 2022-05-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
        ('announcements', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='start_date',
            new_name='date',
        ),
        migrations.AddField(
            model_name='announcement',
            name='course',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='course_announcement', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_general',
            field=models.BooleanField(default=False),
        ),
    ]
